//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfLogger")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/critical", ReplyAction="http://tempuri.org/IService1/criticalResponse")]
        void critical(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/critical", ReplyAction="http://tempuri.org/IService1/criticalResponse")]
        System.Threading.Tasks.Task criticalAsync(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/error", ReplyAction="http://tempuri.org/IService1/errorResponse")]
        void error(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/error", ReplyAction="http://tempuri.org/IService1/errorResponse")]
        System.Threading.Tasks.Task errorAsync(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/warning", ReplyAction="http://tempuri.org/IService1/warningResponse")]
        void warning(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/warning", ReplyAction="http://tempuri.org/IService1/warningResponse")]
        System.Threading.Tasks.Task warningAsync(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/info", ReplyAction="http://tempuri.org/IService1/infoResponse")]
        void info(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/info", ReplyAction="http://tempuri.org/IService1/infoResponse")]
        System.Threading.Tasks.Task infoAsync(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/debug", ReplyAction="http://tempuri.org/IService1/debugResponse")]
        void debug(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/debug", ReplyAction="http://tempuri.org/IService1/debugResponse")]
        System.Threading.Tasks.Task debugAsync(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        CarWebApp.ServiceReference1.CompositeType GetDataUsingDataContract(CarWebApp.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CarWebApp.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(CarWebApp.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CarWebApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CarWebApp.ServiceReference1.IService1>, CarWebApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void critical(string Text) {
            base.Channel.critical(Text);
        }
        
        public System.Threading.Tasks.Task criticalAsync(string Text) {
            return base.Channel.criticalAsync(Text);
        }
        
        public void error(string Text) {
            base.Channel.error(Text);
        }
        
        public System.Threading.Tasks.Task errorAsync(string Text) {
            return base.Channel.errorAsync(Text);
        }
        
        public void warning(string Text) {
            base.Channel.warning(Text);
        }
        
        public System.Threading.Tasks.Task warningAsync(string Text) {
            return base.Channel.warningAsync(Text);
        }
        
        public void info(string Text) {
            base.Channel.info(Text);
        }
        
        public System.Threading.Tasks.Task infoAsync(string Text) {
            return base.Channel.infoAsync(Text);
        }
        
        public void debug(string Text) {
            base.Channel.debug(Text);
        }
        
        public System.Threading.Tasks.Task debugAsync(string Text) {
            return base.Channel.debugAsync(Text);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CarWebApp.ServiceReference1.CompositeType GetDataUsingDataContract(CarWebApp.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CarWebApp.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(CarWebApp.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
